### PR TITLE
Updated build.sbt to support new dockerfile java:7

### PR DESCRIPTION
**Pull request by acidghost**

### CODE REVIEW

**Comment by sjednac** [comment]
Hi @acidghost!

Having a separate MongoDB container is definitely the way to go - thanks for the contribution!

~~I would prefer to skip the `-v <local-mongodb-path>:/data/db` option when launching MongoDB, since there might be a version conflict, and it's not really an "isolated" approach.~~ **Edit:** I guess this would be a good approach in production (I haven't thought about it to be perfectly honest) :)

In any case, I think the only missing part is the sample data [import instruction](https://github.com/sbilinski/scalatra-mongodb-seed/blob/master/data/README.md) for the MongoDB container - would you like to add it, or should I do it myself?

**Comment by acidghost** [comment]
Now I'm at work, as soon as I get home I'll be happy to push the changes ;)

**Comment by acidghost** [comment]
I think it's fine now, did you tried it out in your env?

**Comment by sjednac** [comment]
I tested this a little bit and adjusted the README(s) accordingly. Thanks again for your input - I think it's a really nice addition to the project.

**Pull request merged**
